name: logging_config
version: 0.6.7+5
homepage: https://github.com/SunnyApp/logging_config
description: A plugin that makes it easier to configure logging handlers and output, including loggers in isolates
environment: 
  sdk: '>=2.12.0 <3.0.0'
  flutter: '<3.0.0'
dependencies: 
  js: ^0.6.3
  logging: ^1.0.0
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_test: 
    sdk: flutter
