name: logging_config
version: 0.5.7+2
homepage: https://github.com/SunnyApp/logging_config
description: A plugin that makes it easier to configure logging handlers and output, including loggers in isolates
environment: 
  sdk: '>=2.6.0 <3.0.0'
  flutter: '<3.0.0'
dependencies: 
  js: ^0.6.3
  logging: ^1.0.0
  sunny_dart: ^0.6.0+4
  worker_service: ^0.6.2+4
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: null
